name: CI Stats

on:
  push:
    branches:
      - master
      - main
    paths:
      - lib/stats/**
  pull_request:
    branches:
      - master
      - main
    paths:
      - lib/stats/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Create new image
      - name: Build and push Docker image
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: ${{ secrets.DOCKER_REGISTRY }}
          repository: ${{ github.repository }}-stats
          path: lib/stats/
          tags: latest,${{ github.sha }}

  deploy:
    needs: build
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: azure/k8s-set-context@v1
        with:
          method: service-account
          k8s-url: ${{ secrets.K8S_API_URL }}
          k8s-secret: ${{ secrets.K8S_SECRET }}
      - name: Deploy
        uses: azure/k8s-deploy@v1
        with:
          namespace: stigok
          manifests: |
            lib/stats/manifests/deployment.yaml
            lib/stats/manifests/service.yaml
            lib/stats/manifests/ingress.yaml
          images: |
            ${{ secrets.DOCKER_REGISTRY }}/${{ github.repository }}-stats:${{ github.sha}}
